[package]
name = "medialoop"
version = "0.1.0"
edition = "2021"

[dependencies]
clokwerk = "0.4.0"
crossterm = "0.28.1"
dotenvy = "0.15.7"
home = "0.5.9"
ratatui = "0.29.0"
ratatui-explorer = "0.1.3"
regex = "1.11.1"
strum = {version = "0.26.3", features = ["derive"] }
tui-textarea = "0.7.0"
